version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "00:00"
    reviewers:
      - "kzscisoft"
      - "electricitybender"
    commit-message:
      prefix: "pip"
      include: "scope"
    open-pull-requests-limit: 5
    target-branch: "main"
