exclude: '^tests|^benchmarks|^docs'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-toml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix, "--ignore=C901" ]
      - id: ruff-format
  - repo: https://github.com/conorfalvey/check_pdb_hook
    rev: 0.0.9
    hooks:
      - id: check_pdb_hook
        pass_filenames: false

  - repo: https://github.com/PyCQA/bandit.git
    rev: 1.7.9
    hooks:
    -   id: bandit
        args: [-lll, --recursive, clumper]
