exclude: '^tests|^benchmarks|^docs'
repos:
  - repo: https://github.com/hakancelikdev/unimport
    rev: 0.9.4
    hooks:
      - id: unimport
        args:
          ['--remove', '--check', '--include-star-import']
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.11.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-toml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        args: []
        additional_dependencies:
          - types-PyYAML==6.0.1
          - types-requests==2.26.3
          - types-setuptools==57.4.5
          - types-Jinja2>=2.11.9
          - types-toml>=0.10.3
          - typed-ast>=1.5.2
          - types-pkg-resources>=0.1.3
          - pydantic>=2.0.0
