[tool.poetry]
name = "power_balance"
version = "1.1.0"
description = "Python interface for the tokamak power balance model"
authors = [
    "Alexander Petrov <alexander.petrov@ukaea.uk>",
    "Kristian Zarebski <kristian.zarebski@ukaea.uk>",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)",
    "Natural Language :: English",
    "Operating System :: Unix",
    "Programming Language :: Other",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Physics",
    "Typing :: Typed"
]
keywords = [
    "tokamak",
    "reactor physics",
    "fusion",
    "research"
]

[tool.poetry.dependencies]
python = "^3.8,<3.11"
pandas = "^1.4.2"
matplotlib = "^3.5.1"
prettytable = "^3.3.0"
html2text = "^2020.1.16"
numpy = "^1.22.3"
toml = "^0.10.2"
tables = "^3.7.0"
bokeh = "^2.4.2"
Jinja2 = "^3.0.3"
scipy = "^1.8.0"
click = "^8.1.3"
pydantic = "^1.9.0"
pydelica = "^0.4.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
flake8 = "^4.0.1"
pylint = "^2.12.2"
readability-lxml = "^0.8.1"
coverage = "^6.3"
bandit = "^1.7.4"
anybadge = "^1.9.0"
pyinstrument = "^4.1.1"
mkdocs = "^1.3.0"
mkdocs-material = "^8.2.7"
mkdocs-coverage = "^0.2.5"
pymdown-extensions = "^9.4"
mkdocs-mermaid2-plugin = "^0.5.2"
asv = "^0.5.1"
virtualenv = "^20.14.1"
PyYAML = "^6.0"
deepdiff = "^5.8.0"
mypy = "^0.942"
mkdocs-git-revision-date-localized-plugin = "^1.0.1"
types-PyYAML = "^6.0.7"
types-pkg-resources = "^0.1.3"
types-toml = "^0.10.3"
typed-ast = "^1.5.2"
types-Jinja2 = "^2.11.9"
mkdocs-click = "^0.7.0"
pre-commit = "^2.18.1"
unimport = "^0.9.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
powerbalance = 'power_balance.cli:powerbalance'
