[tool.poetry]
name = "power_balance"
version = "1.1.0"
description = "Python interface for the tokamak power balance model"
authors = [
    "Alexander Petrov <alexander.petrov@ukaea.uk>",
    "Kristian Zarebski <kristian.zarebski@ukaea.uk>",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)",
    "Natural Language :: English",
    "Operating System :: Unix",
    "Programming Language :: Other",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Physics",
    "Typing :: Typed"
]
keywords = [
    "tokamak",
    "reactor physics",
    "fusion",
    "research"
]

[tool.poetry.dependencies]
python = "^3.8,<3.11"
pandas = "^1.5.3"
matplotlib = "^3.7.1"
prettytable = "^3.5.0"
html2text = "^2020.1.16"
numpy = "^1.24.2"
toml = "^0.10.2"
tables = "^3.8.0"
Jinja2 = "^3.0.3"
scipy = "^1.10.1"
click = "^8.1.3"
pydantic = "^1.10.7"
pydelica = "^0.4.3"
bokeh = "^3.1.0"

[tool.poetry.group.dev.dependencies]
flake8 = "^5.0.4"
pylint = "^2.16.4"
readability-lxml = "^0.8.1"
coverage = "^7.2"
bandit = "^1.7.5"
anybadge = "^1.14.0"
pyinstrument = "^4.3.0"
asv = "^0.5.1"
virtualenv = "^20.21.0"
PyYAML = "^6.0"
deepdiff = "^6.3.0"
mypy = "^1.2"
types-PyYAML = "^6.0.12"
types-pkg-resources = "^0.1.3"
types-toml = "^0.10.8"
typed-ast = "^1.5.4"
types-Jinja2 = "^2.11.9"
pre-commit = "^3.1.1"
unimport = "^0.16.0"
pytest = "^7.3.0"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.3.1"
mkdocs-material = "^9.1.5"
mkdocs-coverage = "^0.2.5"
pymdown-extensions = "^9.10"
mkdocs-mermaid2-plugin = "^0.6.0"
mkdocs-click = "^0.8.0"
mkdocs-git-revision-date-localized-plugin = "^1.2.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
powerbalance = 'power_balance.cli:powerbalance'
