name: Remove old artifacts

on: [workflow_dispatch]

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '360 seconds'
