name: Power Balance Models
on: [push]
jobs:
  test_modelica_build:
    name: Test Modelica Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: artemis-beta/setup-openmodelica@v2
        with:
          msl-version: '3.2.3'
      - name: Compile models
        run: |
          mkdir build
          cd build
          for i in $(ls ${CI_PROJECT_DIR}/power_balance/models/*.mo); do omc -s $i; done
          for i in $(ls *.makefile); do make -f $i; done
        shell: bash

