name: PBM Code Quality
on: [pull_request]
jobs:
  type_validation:
    name: Mypy Type Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Mypy
        run: |
          poetry install 
          poetry run mypy power_balance/
  modelica_syntax_validation:
    name: Modelica Syntax Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Modelica Code Check
        run: |
          git clone https://github.com/modelica-tools/ModelicaSyntaxChecker.git
          ${GITHUB_WORKSPACE}/ModelicaSyntaxChecker/Linux64/moparser -c -l -r power_balance/
  bandit_security_check:
    name: Bandit Security Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mdegis/bandit-action@v1.0
        with: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ini_path: bandit.yml
          exit_zero: false
          path: power_balance
