name: PBM Code Quality
on: [pull_request]
jobs:
  type_validation:
    name: Mypy Type Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Mypy
        uses: tsuyoshicho/action-mypy@v3.4.0
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          workdir: power_balance
          fail_on_error: true # capture typing issues before they become part of main code
  modelica_syntax_validation:
    name: Modelica Syntax Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Modelica Code Check
        run: |
          git clone https://github.com/modelica-tools/ModelicaSyntaxChecker.git
          ${GITHUB_WORKSPACE}/ModelicaSyntaxChecker/Linux64/moparser -c -l -r power_balance/
  bandit_security_check:
    name: Bandit Security Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mdegis/bandit-action@v1.0
        with: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ini_path: bandit.yml
          exit_zero: false
          path: power_balance
