name: PBM Code Quality
on: [pull_request]
jobs:
  type_validation:
    name: Mypy Type Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "1.2.2"
      - name: Run Mypy
        run: |
          poetry install 
          poetry run mypy power_balance/
  modelica_syntax_validation:
    name: Modelica Syntax Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Modelica Code Check
        run: |
          git clone https://github.com/modelica-tools/ModelicaSyntaxChecker.git
          ${GITHUB_WORKSPACE}/ModelicaSyntaxChecker/Linux64/moparser -c -l -r power_balance/
  
  bandit_security_check:
    name: Bandit Security Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jpetrucciani/bandit-check@master
        with: 
          bandit_flags: '-c bandit.yml'
          path: power_balance

  import_sort:
    name: Run Python Import Order Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Check Imports
        uses: isort/isort-action@master
        with:
          configuration: '--check-only --diff --profile black'

  black_linter:
    name: Run Black Python Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Code with Black
        uses: psf/black@stable
        with:
          src: power_balance

  unused_imports:
    name: Run Unused Python Import Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install Unimport
        run: python -m pip install unimport
      - name: Check Imports
        run: unimport --check --diff --include power_balance
