name: PBM Code Quality
on: [pull_request]
jobs:
  type_validation:
    name: Mypy Type Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - uses: Gr1N/setup-poetry@v7
      - name: Run Mypy
        run: |
          poetry install 
          poetry run mypy power_balance/
  modelica_syntax_validation:
    name: Modelica Syntax Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Modelica Code Check
        run: |
          git clone https://github.com/modelica-tools/ModelicaSyntaxChecker.git
          ${GITHUB_WORKSPACE}/ModelicaSyntaxChecker/Linux64/moparser -c -l -r power_balance/
  
  bandit_security_check:
    name: Bandit Security Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jpetrucciani/bandit-check@master
        with: 
          bandit_flags: '-c bandit.yml'
          path: power_balance

  import_sort:
    name: Run Python Import Order Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Check Imports
        uses: isort/isort-action@master

  black_linter:
    name: Run Black Python Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Code with Black
        uses: psf/black@stable

