name: Deploy Power Balance Models
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  deploy_ubuntu:
    name: Deploy Latest Ubuntu Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: Gr1N/setup-poetry@v8
      - name: Check Citation File
        run: |
          python3 -m pip install -r <(curl -s https://raw.githubusercontent.com/citation-file-format/citation-file-format/main/requirements.txt)
          python3 <(curl -s https://raw.githubusercontent.com/citation-file-format/citation-file-format/main/examples/validator.py) \
            -d ${GITHUB_WORKSPACE}/CITATION.cff \
            -s <(curl -s https://raw.githubusercontent.com/citation-file-format/citation-file-format/main/schema.json)
      - name: Install Module
        run: poetry install
      - name: Build Module
        run: poetry build
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          name: Power Balance Models Release ${{ steps.previoustag.outputs.tag }}
          tag_name: ${{ steps.previoustag.outputs.tag }}
          files: |
            dist/*.whl
            dist/*.gz
